default_settings: null
behaviors:
  Lizard:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      rnd:
        gamma: 0.99
        strength: 0.01
        network_settings:
          normalize: false
          hidden_units: 64
          num_layers: 3
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.0001
        encoding_size: null
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 50000000
    max_steps: 500000000
    time_horizon: 128
    summary_freq: 30000
    threaded: false
    self_play: null
    behavioral_cloning: null